import { notFound } from 'next/navigation'
import Link from 'next/link'
import { ArrowLeft, FileText, ExternalLink } from 'lucide-react'
import { getBillBySlug, getAllBills } from '@/lib/wiki'
import PartyBadge from '@/components/PartyBadge'
import VoteBadge from '@/components/VoteBadge'
import BillStatusBar from '@/components/BillStatusBar'

export async function generateStaticParams() {
  const bills = await getAllBills()
  return bills.map((b) => ({ slug: b.slug }))
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const bill = await getBillBySlug(slug)
  if (!bill) return {}
  return {
    title: `${bill.title} — MyReps.info`,
    description: bill.summary ?? `Details and voting record for ${bill.title}.`,
  }
}

export default async function BillPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const bill = await getBillBySlug(slug)
  if (!bill) notFound()

  const votes = bill.votes ?? []
  const yeaVotes = votes.filter((v) => v.vote === 'Yea')
  const nayVotes = votes.filter((v) => v.vote === 'Nay')
  const otherVotes = votes.filter((v) => v.vote !== 'Yea' && v.vote !== 'Nay')

  return (
    <div className="max-w-4xl mx-auto px-4 py-8 space-y-10">
      {/* Back */}
      <Link
        href="/"
        className="inline-flex items-center gap-1 text-sm text-gray-500 hover:text-civic-blue no-underline"
      >
        <ArrowLeft className="w-4 h-4" />
        Back to search
      </Link>

      {/* Header */}
      <div className="bg-white rounded-xl border border-gray-200 p-6 space-y-4">
        <div className="flex items-start gap-3">
          <FileText className="w-6 h-6 text-civic-blue flex-shrink-0 mt-1" />
          <div className="flex-1 space-y-1">
            <div className="flex flex-wrap items-center gap-2">
              <span className="text-sm font-mono text-gray-500">{bill.id}</span>
              {bill.congress && (
                <span className="text-xs text-gray-400">{bill.congress}th Congress</span>
              )}
            </div>
            <h1 className="text-2xl font-bold text-gray-900 leading-tight">{bill.title}</h1>
          </div>
        </div>

        {/* Metadata row */}
        <div className="flex flex-wrap gap-4 text-sm text-gray-500">
          {bill.sponsor_name && (
            <span>
              Sponsored by{' '}
              {bill.sponsor_slug ? (
                <Link href={`/politician/${bill.sponsor_slug}`} className="text-civic-blue font-medium">
                  {bill.sponsor_name}
                </Link>
              ) : (
                <span className="font-medium">{bill.sponsor_name}</span>
              )}
            </span>
          )}
          {bill.date_introduced && (
            <span>
              Introduced{' '}
              {new Date(bill.date_introduced).toLocaleDateString('en-US', {
                month: 'long',
                day: 'numeric',
                year: 'numeric',
              })}
            </span>
          )}
          {bill.cosponsor_count != null && (
            <span>{bill.cosponsor_count} cosponsors</span>
          )}
          {bill.full_text_url && (
            <a
              href={bill.full_text_url}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1 text-civic-blue hover:underline"
            >
              <ExternalLink className="w-3.5 h-3.5" />
              Full text
            </a>
          )}
        </div>

        {/* Status bar */}
        <div className="pt-2">
          <BillStatusBar status={bill.status} />
        </div>
      </div>

      {/* Summary */}
      <section>
        <h2 className="text-xl font-semibold text-gray-900 border-b pb-2 mb-4">
          Plain-English Summary
          {bill.summary_source === 'claude' && (
            <span className="ml-2 text-xs font-normal text-gray-400 bg-gray-100 px-2 py-0.5 rounded">
              Generated by Claude
            </span>
          )}
        </h2>

        {bill.summary_html ? (
          <div
            className="prose-wiki text-gray-700 leading-relaxed"
            dangerouslySetInnerHTML={{ __html: bill.summary_html }}
          />
        ) : bill.summary ? (
          <p className="text-gray-700 leading-relaxed">{bill.summary}</p>
        ) : (
          <p className="text-gray-400 text-sm">Summary not yet available.</p>
        )}
      </section>

      {/* Subjects / tags */}
      {bill.subjects && bill.subjects.length > 0 && (
        <section>
          <h2 className="text-xl font-semibold text-gray-900 border-b pb-2 mb-4">Policy Areas</h2>
          <div className="flex flex-wrap gap-2">
            {bill.subjects.map((subject) => (
              <span
                key={subject}
                className="text-sm bg-civic-light text-civic-blue px-3 py-1 rounded-full"
              >
                {subject}
              </span>
            ))}
          </div>
        </section>
      )}

      {/* Vote breakdown */}
      {votes.length > 0 && (
        <section>
          <h2 className="text-xl font-semibold text-gray-900 border-b pb-2 mb-4">
            Voting Record{' '}
            <span className="text-sm font-normal text-gray-400">({votes.length} votes)</span>
          </h2>

          {/* Tally */}
          <div className="grid grid-cols-3 gap-4 mb-6">
            <div className="bg-green-50 border border-green-200 rounded-lg p-4 text-center">
              <p className="text-3xl font-bold text-green-700">{yeaVotes.length}</p>
              <p className="text-sm text-green-600 font-medium">Yea</p>
            </div>
            <div className="bg-red-50 border border-red-200 rounded-lg p-4 text-center">
              <p className="text-3xl font-bold text-red-700">{nayVotes.length}</p>
              <p className="text-sm text-red-600 font-medium">Nay</p>
            </div>
            <div className="bg-gray-50 border border-gray-200 rounded-lg p-4 text-center">
              <p className="text-3xl font-bold text-gray-500">{otherVotes.length}</p>
              <p className="text-sm text-gray-500 font-medium">Other</p>
            </div>
          </div>

          {/* Vote table */}
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="text-left text-xs text-gray-500 border-b border-gray-200">
                  <th className="pb-2 pr-4 font-medium">Name</th>
                  <th className="pb-2 pr-4 font-medium">Party</th>
                  <th className="pb-2 pr-4 font-medium hidden sm:table-cell">State</th>
                  <th className="pb-2 pr-4 font-medium hidden sm:table-cell">Chamber</th>
                  <th className="pb-2 font-medium">Vote</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {votes.map((vote, i) => (
                  <tr key={i} className="hover:bg-gray-50">
                    <td className="py-3 pr-4 font-medium">
                      {vote.politician_slug ? (
                        <Link href={`/politician/${vote.politician_slug}`} className="text-civic-blue hover:underline">
                          {vote.politician_name}
                        </Link>
                      ) : (
                        vote.politician_name
                      )}
                    </td>
                    <td className="py-3 pr-4">
                      <PartyBadge party={vote.party} short />
                    </td>
                    <td className="py-3 pr-4 text-gray-500 hidden sm:table-cell">{vote.state}</td>
                    <td className="py-3 pr-4 text-gray-500 hidden sm:table-cell">{vote.chamber}</td>
                    <td className="py-3">
                      <VoteBadge vote={vote.vote} />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>
      )}

      {/* Timeline */}
      <section>
        <h2 className="text-xl font-semibold text-gray-900 border-b pb-2 mb-4">Timeline</h2>
        <div className="space-y-2">
          {bill.date_introduced && (
            <TimelineItem date={bill.date_introduced} label="Introduced" />
          )}
          {bill.date_passed_house && (
            <TimelineItem date={bill.date_passed_house} label="Passed House" />
          )}
          {bill.date_passed_senate && (
            <TimelineItem date={bill.date_passed_senate} label="Passed Senate" />
          )}
          {bill.date_signed && (
            <TimelineItem date={bill.date_signed} label="Signed into Law" highlight />
          )}
        </div>
      </section>

      {bill.last_updated && (
        <p className="text-xs text-gray-400 text-right">
          Data last updated: {new Date(bill.last_updated).toLocaleDateString()}
        </p>
      )}
    </div>
  )
}

function TimelineItem({
  date,
  label,
  highlight = false,
}: {
  date: string
  label: string
  highlight?: boolean
}) {
  return (
    <div className="flex items-center gap-3 text-sm">
      <div className={`w-2 h-2 rounded-full flex-shrink-0 ${highlight ? 'bg-green-500' : 'bg-civic-blue'}`} />
      <span className={highlight ? 'font-semibold text-green-700' : 'text-gray-700'}>{label}</span>
      <span className="text-gray-400">
        {new Date(date).toLocaleDateString('en-US', {
          month: 'long',
          day: 'numeric',
          year: 'numeric',
        })}
      </span>
    </div>
  )
}
