import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'About — MyReps.info',
  description: 'Learn how MyReps.info works and where our data comes from.',
}

export default function AboutPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12 space-y-12">
      <div>
        <h1 className="text-4xl font-bold text-gray-900 mb-3">About MyReps.info</h1>
        <p className="text-xl text-gray-500 leading-relaxed">
          A nonpartisan, open reference site for every elected official in the United States —
          local, state, and federal.
        </p>
      </div>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-gray-900 border-b pb-2">What We Do</h2>
        <p className="text-gray-700 leading-relaxed">
          MyReps.info lets any American find out who represents them at every level of government
          by entering their ZIP code. For each politician, we show their full voting record on
          every bill they've voted on, every piece of legislation they've sponsored or co-sponsored,
          and how to contact them directly.
        </p>
        <p className="text-gray-700 leading-relaxed">
          Every bill has a plain-English summary so you don't need a law degree to understand
          what your representatives are voting on. Summaries are sourced from the Congressional
          Research Service when available, and generated by Claude (Anthropic's AI) when they aren't.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-gray-900 border-b pb-2">Our Principles</h2>
        <div className="grid sm:grid-cols-3 gap-6">
          {[
            {
              title: 'Nonpartisan',
              desc: 'We present voting records and facts — no editorial framing, no partisan spin. Every politician gets the same treatment.',
            },
            {
              title: 'Transparent',
              desc: 'All data sources are listed. Every bill summary says whether it came from CRS or was AI-generated.',
            },
            {
              title: 'Open',
              desc: 'The site is open source. You can view, audit, or contribute to the code on GitHub.',
            },
          ].map((p) => (
            <div key={p.title} className="bg-civic-light border border-civic-border rounded-lg p-5">
              <h3 className="font-semibold text-gray-900 mb-2">{p.title}</h3>
              <p className="text-sm text-gray-600 leading-relaxed">{p.desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-gray-900 border-b pb-2">Data Sources</h2>
        <div className="space-y-3">
          {[
            {
              name: 'OpenStates',
              url: 'https://openstates.org',
              desc: 'ZIP code lookups and state legislative data for all 50 states.',
            },
            {
              name: 'Congress.gov API',
              url: 'https://api.congress.gov',
              desc: 'Official Library of Congress API for federal members, bills, votes, and CRS summaries.',
            },
            {
              name: 'Nominatim / OpenStreetMap',
              url: 'https://nominatim.openstreetmap.org',
              desc: 'Free geocoding to convert ZIP codes into coordinates for lookups.',
            },
            {
              name: 'Claude (Anthropic)',
              url: 'https://anthropic.com',
              desc: 'Generates plain-English bill summaries when no official CRS summary exists.',
            },
          ].map((s) => (
            <div key={s.name} className="flex gap-4 py-3 border-b border-gray-100">
              <div className="flex-1">
                <a href={s.url} target="_blank" rel="noopener noreferrer" className="font-medium text-civic-blue hover:underline">
                  {s.name}
                </a>
                <p className="text-sm text-gray-500 mt-0.5">{s.desc}</p>
              </div>
            </div>
          ))}
        </div>
        <p className="text-sm text-gray-400">
          Data is refreshed automatically every Sunday. Last-updated dates appear on each profile page.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-gray-900 border-b pb-2">How It Works</h2>
        <p className="text-gray-700 leading-relaxed">
          MyReps.info uses a &ldquo;LLM Wiki&rdquo; architecture inspired by{' '}
          <a href="https://gist.github.com/karpathy/442a6bf555914893e9891c11519de94f" target="_blank" rel="noopener noreferrer" className="text-civic-blue hover:underline">
            Andrej Karpathy&apos;s LLM knowledge base pattern
          </a>
          . A background pipeline runs weekly, pulls data from official government APIs, writes
          structured Markdown articles for every politician and bill, and publishes them as a
          static site. This means pages load instantly and the site works even if upstream APIs
          are temporarily unavailable.
        </p>
        <p className="text-gray-700 leading-relaxed">
          All editorial decisions — what data to show, how summaries are worded, what sources
          are trusted — are made by the site team and enforced through the pipeline. No
          user-submitted content is accepted.
        </p>
      </section>

      <div className="text-center pt-4">
        <Link
          href="/"
          className="inline-block bg-civic-navy text-white font-semibold px-8 py-3 rounded-lg hover:bg-blue-900 transition-colors no-underline"
        >
          Find My Representatives
        </Link>
      </div>
    </div>
  )
}
